### ISSUE TITLE
[LoadDigraph] edge to subgraph

### ISSUE THREAD

**Issue by harshsikhwal** [harshsikhwal/csdot#14]
File: 

Resources\test\Issues\[LoadDigraph] edge to subgraph\edge_subgraph.dot
Resources\test\Issues\[LoadDigraph] edge to subgraph\large_graphs1.dot
Resources\test\Issues\[LoadDigraph] edge to subgraph\large_graphs2.dot

Throws stack empty exception.

**Comment by Vibaswan** [comment]
Will work thanks for pointing out

**Comment by Vibaswan** [comment]
issue fixed 
please see commit 3825b9a276ec8b0e7cc8f001fbe91f8b8c3e9838
