### ISSUE TITLE
[LoadDigraph] graph-digraph is not preserved 

### ISSUE THREAD

**Issue by harshsikhwal** [harshsikhwal/csdot#15]
File: Resources\test\Issues\[LoadDigraph] graph-digraph is not preserved\full_diagraph.dot

1. digraph keyword is not preserved
2. For null graph name/id, Default is added. Prevent that

**Comment by Vibaswan** [comment]
issue fixed 
please see commit 3825b9a276ec8b0e7cc8f001fbe91f8b8c3e9838
