### ISSUE TITLE
[LoadDigraph] Add support for nested subgraphs

### ISSUE THREAD

**Issue by harshsikhwal** [harshsikhwal/csdot#25]
File:
Resources\test\Issues\[LoadDigraph] Add support for nested subgraphs\nested_cluster.dot
Resources\test\Issues\[LoadDigraph] Add support for nested subgraphs\subgraph_cluster.dot

Add support for nested subgraphs/subgraph-clusters and vice versa

**Comment by Vibaswan** [comment]
issue fixed 
please see commit 3825b9a276ec8b0e7cc8f001fbe91f8b8c3e9838
