### ISSUE TITLE
The project should be buildable using the dotnet build command

### ISSUE THREAD

**Issue by rajarshipoddar** [harshsikhwal/csdot#32]
**dotnet build** command produces the following error:

Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\rapoddar\github\csdot\src\test\test.csproj (in 207 ms).
  Restored C:\Users\rapoddar\github\csdot\src\csdot\csdot.csproj (in 257 ms).
  Restored C:\Users\rapoddar\github\csdot\src\UnitTest\UnitTest.csproj (in 13.76 sec).
    File "attribute_generator/code_generator.py", line 261
  SyntaxError: Non-ASCII character '\xc2' in file attribute_generator/code_generator.py on line 262, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
C:\Users\rapoddar\github\csdot\src\csdot\csdot.csproj(31,3): error MSB3073: The command "python attribute_generator/code_generator.py" exited with code 1.
    File "attribute_generator/code_generator.py", line 261
  SyntaxError: Non-ASCII character '\xc2' in file attribute_generator/code_generator.py on line 262, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
C:\Users\rapoddar\github\csdot\src\csdot\csdot.csproj(31,3): error MSB3073: The command "python attribute_generator/code_generator.py" exited with code 1.

Build FAILED.

C:\Users\rapoddar\github\csdot\src\csdot\csdot.csproj(31,3): error MSB3073: The command "python attribute_generator/code_generator.py" exited with code 1.
C:\Users\rapoddar\github\csdot\src\csdot\csdot.csproj(31,3): error MSB3073: The command "python attribute_generator/code_generator.py" exited with code 1.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:24.90

**--- To Fix the issue need to add the below lines at the top of python file attribute_generator/code_generator.py--**

#!/usr/bin/python
\# -*- coding: utf-8 -*-

**Comment by rajarshipoddar** [comment]
I am running this on windows

**Comment by Vibaswan** [comment]
Actually we build the project through Github actions you can refer to the file https://github.com/harshsikhwal/csdot/blob/main/.github/workflows/build_and%20release.yml
we use the same command in the windows environment, you can look at the logs 
https://github.com/harshsikhwal/csdot/runs/2431859644?check_suite_focus=true 
The default python path is generally taken up 
The issue arises when we use python 2 for building
Thanks for pointing out the issue 👍 
We have fixed it.
